### ISSUE TITLE
Update Projects and Events

### ISSUE THREAD

**Issue by GeekBoySupreme** [DSC-HIT/DSC-HIT-Website#56]
The Projects and Events of DSC HIT have to be updated in their respective JSONs to keep the website up to date with the events that have happened.

**Comment by drwm-base** [comment]
Hi, I'd like to help with this, but could you give me some more information as to what needs to be updated?

**Comment by GeekBoySupreme** [comment]
Hey,
So glad you want to help out. Would be floating a document that contains the details that need to put formatted and put in the respective JSON Files 27th Oct EOD.

Keep an eye out in this comment section.
