### ISSUE TITLE
Update events.json

### ISSUE THREAD

**Issue by GeekBoySupreme** [DSC-HIT/DSC-HIT-Website#58]
Updating the Events for DSC HIT with by adding the events listed in the document linked below : https://docs.google.com/document/d/1XQO0bShtgzJdypdFbELOCTumQFsEiLCIe1sDGBo5ysM/edit?usp=sharing

**Comment by dvrzan** [comment]
Hi! What do you need help here with? Where can I see the events you want added to the events.json?

**Comment by GeekBoySupreme** [comment]
> Hi! What do you need help here with? Where can I see the events you want added to the events.json?

Hey, linking the document containing the event details. 
https://docs.google.com/document/d/1XQO0bShtgzJdypdFbELOCTumQFsEiLCIe1sDGBo5ysM/edit?usp=sharing
Hope this helps.

**Comment by lizwait** [comment]
Working on this now @GeekBoySupreme! :) I can't find the image for the first event. Everything else is almost done.
