### ISSUE TITLE
Update projects.json

### ISSUE THREAD

**Issue by GeekBoySupreme** [DSC-HIT/DSC-HIT-Website#59]

**Comment by abhinavkrin** [comment]
Where can I find the details of the projects?

**Comment by GeekBoySupreme** [comment]
Hey, we have a Dashboard now from where we update these data. This issue is redundant now.

**Comment by GeekBoySupreme** [comment]
Hey, we have a Dashboard now from where we update these data. This issue is redundant now.

**Comment by GeekBoySupreme** [comment]
Hey, we have a Dashboard now from where we update these data. This issue is redundant now.
