### ISSUE TITLE
Adding Loaders to screens that fetch data from Dashboard

### ISSUE THREAD

**Issue by GeekBoySupreme** [DSC-HIT/DSC-HIT-Website#92]
Use Lottie animations as a placeholder Loader in Projects, events, team until the actual data is fetched and loaded.
For example - https://lottiefiles.com/34884-yummy-yummy

**Comment by BhupaliRane** [comment]
Can I work on this

**Comment by GeekBoySupreme** [comment]
Sure. Feel free to send forth a PR.

**Comment by GeekBoySupreme** [comment]
Thanks for the contribution @BhupaliRane
